// Yetkili hastane listesi (oto-tamamlama ve doğrulama için)
export const HOSPITALS: string[] = [
"100. Yıl Hastanesi",
"100. Yıl Üniversitesi",
"29 Mayıs Devlet Hastanesi",
"Abant İzzet Baysal Üniversitesi",
"Acıbadem Adana Hastanesi",
"Acıbadem Altunizade Hastanesi",
"Acıbadem Atakent Hastanesi",
"Acıbadem Ataşehir Hastanesi",
"Acıbadem Bakırköy Hastanesi",
"Acıbadem Bursa Hastanesi",
"Acıbadem Eskişehir Hastanesi",
"Acıbadem Kadıköy Hastanesi",
"Acıbadem Kocaeli Hastanesi",
"Acıbadem Maslak Hastanesi",
"Adana Özel Sağlık Hastanesi",
"Adana Şehir Hastanesi",
"Adıyaman Üniversitesi Eğitim Araştırma Hastanesi",
"Adnan Menderes Üniversitesi",
"Afyon Park Hastanesi",
"Afyonkarahisar Devlet Hastanesi",
"Ahi Evren GKDC Eğitim ve Araştırma Hastanesi",
"Aile Hastanesi Bahçelievler",
"Akay Hastanesi",
"Akdeniz Üniversitesi",
"Aksaray Devlet Hastanesi",
"Alanya Eğitim Araştırma Hastanesi",
"Amerikan Hastanesi",
"Anadolu Sağlık Merkezi",
"Anka Hastanesi",
"Ankara Hastanesi",
"Ankara Şehir Hastanesi",
"Ankara Üniversitesi Cebeci Kalp Merkezi",
"Antalya Eğitim Araştırma Hastanesi",
"Antalya Eğt.Arş.Hastanesi",
"Atatürk Üniversitesi",
"Avcılar Hospital",
"Avicenna Esenler Hastanesi",
"Avrasiya Hospital",
"Avrasya Hospital",
"Avrupa Şafak Hastanesi",
"Aydın Adnan Menderes Üniversitesi",
"Aydın Devlet Hastanesi",
"Azərbaycan Tibb Universiteti Cərahiyyə Xəstəxanası",
"Bağcılar Eğitim ve Araştırma Hastanesi",
"Bahar Hastanesi",
"Bakırköy Sadi Konuk Eğitim ve Araştırma Hastanesi",
"Baki Uzun Hastanesi",
"Balıkesir Atatürk ŞehirHastanesi",
"Balıkesir Devlet Hastanesi",
"Balıkesir Sevgi Hastanesi",
"Balıkesir Şehir Hastanesi",
"Balıkesir Üniversite Hastanesi",
"Balıkesir Üniversitesi",
"Bandırma Devlet Hastanesi",
"Bandırma Eğt.Arş.Hastanesi",
"Başakşehir Çam ve Sakura Şehir Hastanesi",
"Başkent Üniversitesi Adana Yüreğir",
"Başkent Üniversitesi Ankara",
"Başkent Üniversitesi İstanbul",
"Başkent Üniversitesi Konya",
"Başkent Üniversitesi Seyhan Hastanesi",
"Başkent Üniversitesi Yüreğir Hastanesi",
"Batman Eğiti Araştırma Hastanesi",
"Bayındır Hastanesi Ankara",
"Bayındır İçerenköy Hastanesi",
"Behçet Uz Eğitim ve Araştırma Çocuk Hastanesi",
"Beykent Üniversitesi Hastanesi",
"Bezm-i Alem Üniversitesi",
"Bilecik Eğitim ve Araştırma Hastanesi",
"Bilgi Hastanesi",
"Bingöl Devlet Hastanesi",
"Biruni Üniversite Hastanesi",
"Bodrum Acıbadem Hastanesi",
"Bower Hospital",
"Buca Seyfi Demirsoy Devlet Hastanesi",
"Bursa Anadolu Hastanesi",
"Bursa Devlet Hastanesi",
"Bursa Şehir Hastanesi",
"Bursa Yüksek İhtisas Hastanesi",
"Celal Bayar Üniversitesi Hastanesi",
"Central Hastanesi",
"Cumhuriyet Üniversitesi",
"Çakmak Erdem Hastanesi",
"Çamlıca Erdem Hastanesi",
"Çankaya Hastanesi",
"Çekirge Kalp ve Aritmi Hastanesi",
"Çiğli Bölge Hastanesi",
"Çorlu Devlet Hastanesi",
"Çorlu Şifa Hastanesi",
"Çukurova Devlet Hastanesi",
"Damla Hastanesi",
"Defne Hastanesi",
"Denizli Cerrahi Hastanesi",
"Denizli Devlet Hastanesi",
"Denizli Özel Ege Kent Hastanesi",
"Denizli Özel Erpa Hastanesi",
"Derince Eğtim ve Araştırma Hastanesi",
"Dicle Üniversitesi",
"Diyarbakır Memorial Hospital",
"Doğan Hastanesi",
"Dokuz Eylül Üniversitesi",
"Dr. İsmail Fehmi Cumalıoğlu Şehir Hastanesi",
"Dr.Ersin Arslan Eğitim ve Araştırma Hastanesi",
"Dumlupınar Üniversitesi Evliya Çelebi Eğitim ve Araştırma Hastanesi",
"Dünya Hastanesi",
"Düzce Üniversitesi",
"Edirne Devlet Hastanesi",
"EGE Hospital",
"Ege Üniversitesi",
"Emsey Hospital",
"Erciyes Üniversitesi",
"Erzincan Üniversitesi Mengücek Gazi Eğt. Araşt. Hast.",
"Erzurum Şehir Hastanesi",
"Eskişehir Anadolu Hastanesi",
"Eskişehir Şehir Hastanesi",
"Etlik Şehir Hastanesi",
"Experimental Hastane",
"Fethi Sekin Şehir Hastanesi",
"Fethiye Lokman Hekim Hastanesi",
"Feti Sekin Şehir Hastanesi",
"Fırat Üniversitesi",
"Florence Nightingale Kadıköy Hastanesi",
"Florence Nightingale Şişli Hastanesi",
"Gazi Hastanesi",
"Gazi Üniversitesi",
"Gazi Yaşargil Eğitim Araştırma Hastanesi",
"Gaziantep Medicalpoint Hastanesi",
"Gaziantep Şehir Hastanesi",
"Gaziantep Üniversitesi",
"Gaziosmanpaşa Üniversitesi",
"Gebze Fatih Devlet Hastanesi",
"Gence Beynelxalq Hastane",
"Gəncə Beynəlxalq Hospitalı",
"Giresun Eğitim ve Araştırma Hastanesi",
"Giresun Özel Ada Hastanesi",
"GOP Eğitim ve Araştırma Hastanesi",
"Gözde Hastanesi",
"Gülhane Askeri Tıp Akademisi",
"Güven Hastanesi",
"Hacettepe Üniversitesi",
"Harran Üniversitesi",
"Haseki Eğitim ve Araştırma 29 Mayıs Hastanesi",
"Hayat Hastanesi",
"Herbi Hospital",
"Hisar Intercontinental Hospital",
"Hitit Üniversitesi Çorum Erol Olçak Eğitim ve Araştırma Hastanesi",
"IMC Hastanesi",
"International Hospital",
"Isparta Özel Meddem Hastanesi",
"Isparta Süleyman Demirel Üniversitesi",
"İ.A.Ü. VM Medical Park Florya Hastanesi",
"İnönü Üniversitesi Turgut Özal Tıp Merkezi",
"İstanbul Prof. Dr. Cemil Taşcıoğlu Eğitim ve Araştırma Hastanesi",
"İstanbul Sultan 2.Abdülhamid Han Eğitim ve Araştırma Hastanesi",
"İstanbul Üniversitesi Cerrahpaşa Hastanesi",
"İstanbul Üniversitesi Çapa Hastanesi",
"İstanbul Üniversitesi Kardiyoloji Enstitüsü",
"İstinye Üniversitesi Liv Hospital Hastanesi",
"İstinye Üniversitesi Liv Hospital Hastanesi GOP",
"İye Hospital",
"İzmir Atatürk Eğitim ve Araştırma Hastanesi",
"İzmir Bayraklı Şehir Hastanesi",
"İzmir Ekonomi Üniv.Medical Point Hastanesi",
"İzmir Şehir Hastanesi",
"Kadıköy Alman Hastanesi",
"Kanuni Sultan Süleyman EAH",
"Karadeniz Teknik Üniversitesi Farabi Hastanesi",
"Karaelmas Üniversitesi",
"Kartal Koşuyolu Eğitim ve Araştırma Hastanesi",
"Kavaklıdere Umut Hastanesi",
"Kıbrıs Dr Burhan Nalbantoğlu Devlet Hastanesi",
"Kırıkkale Üniversitesi",
"Kırklareli Devlet Hastanesi",
"Kilis Devlet Hastanesi",
"Kocaeli Şehir Hastanesi",
"Kocaeli Üniversitesi",
"Kocatepe Üniversitesi",
"Koç Üniversitesi Tıp Fakültesi Hastanesi",
"Kolan Bayrampaşa Hastanesi",
"Kolan Beylikdüzü Hastanesi",
"Kolan International Hospital",
"Konak Hastanesi",
"Konya Şehir Hastanesi",
"Koru Hastanesi",
"Körfez Hastanesi",
"Kudret International",
"Kuşadası Universal Hospital",
"Kütahya Eğitim ve Araştırma Hastanesi",
"Kütahya Evliya Çelebi EAH",
"Liv Hospital Ankara",
"Liv Hospital Gaziantep",
"Liv Hospital Vadistanbul",
"Lokman Hekim Hastanesi",
"Malatya Eğitim ve Araştırma Hastanesi",
"Malatya Gözde Akademi Hastanesi",
"Malatya Gözde Hastanesi",
"Maltepe Üniversitesi",
"Manisa Şehir Hastanesi",
"Mardin Devlet Hastanesi",
"Marmara Üniversitesi",
"Medeniyet Üniversitesi Göztepe Eğitim Ve Araştırma Hastanesi",
"Medical Park Antalya Hastanesi",
"Medical Park Bahçelievler Hastanesi",
"Medical Park Bursa Hastanesi",
"Medical Park Elazığ Hastanesi",
"Medical Park Fatih Hastanesi",
"Medical Park Gebze Hastanesi",
"Medical Park Göztepe Hastanesi",
"Medical Park Ordu Hastanesi",
"Medical Park Samsun Hastanesi",
"Medical Park Tokat Hastanesi",
"Medical Point İzmir Hastanesi",
"Medicalpark Elazığ Hastanesi",
"Medicalpark Silivri Hastanesi",
"Medicana Ataköy Hastanesi",
"Medicana Ataşehir Hastanesi",
"Medicana Bahçelievler Hastanesi",
"Medicana Çamlıca Hastanesi",
"Medicana International Ankara Hastanesi",
"Medicana International İstanbul Hastanesi",
"Medicana International Konya Hastanesi",
"Medicana International Samsun Hastanesi",
"Medicana International Sivas Hastanesi",
"Medicana İzmir Hastanesi",
"Medicana Zincirlikuyu Hastanesi",
"Medicine Hastanesi",
"Medifema Hastanesi",
"Medikar Hastanesi",
"Mediland Hospital",
"Medinova Aydın Hastanesi",
"Medipol Üniversitesi Hastanesi",
"Medistate Hastanesi",
"Medline Adana Hastanesi",
"Medline Hastanesi Adana",
"Medline Hastanesi Antalya",
"Medline Hastanesi Aydın",
"Medline Hastanesi Eskişehir",
"Medline Hastanesi Konya",
"Medystyle Hospital",
"Megapark Hastanesi",
"Mehmet Akif Ersoy Eğitim ve Araştırma Hastanesi",
"Mehmet Akif İnan Eğitim Araştırma Hastanesi",
"Mehmet Akif İnan Haliliye Eğitim Araştırma Hastanesi",
"Memorial Ataşehir Hastanesi",
"Memorial Bahçelievler Hastanesi",
"Memorial Hastanesi",
"Memorial Şişli Hastanesi",
"Meram Tıp Fakültesi Hastanesi",
"Mersin Ortadoğu Hastanesi",
"Mersin Şehir Hastanesi",
"Mersin Üniversitesi",
"Muğla Üniversite Hastanesi",
"Muğla Yücelen Hastanesi",
"Mustafa Kemal Üniversitesi",
"Muş Devlet Hastanesi",
"Müjde Hastanesi",
"Namık Kemal Üniversitesi",
"Natomed Hastanesi",
"Nazilli Devlet Hastanesi",
"Ncr Hastanesi",
"Necip Fazıl Şehir Hastanesi",
"Nev Hastanesi",
"Okan Üniversitesi Hastanesi",
"Olimp Hospital",
"Ondokuz Mayıs Üniversitesi",
"Onsekiz Mart Üniversitesi",
"Ordu Üniversitesi",
"Ortadoğu Mersin Hastanesi",
"Osmangazi Üniversitesi",
"Osmaniye Devlet Hastanesi",
"Özel Adana Hastanesi",
"Özel Adatıp Hastanesi",
"Özel Akut Hastanesi",
"Özel Atakalp Hastanesi",
"Özel Batman Hastanesi",
"Özel Ege Sağlık Hastanesi",
"Özel Ege Tıp Hizmetleri",
"Özel Egepol",
"Özel Grand Medical",
"Özel Hizmet Hastanesi",
"Özel IMC Hastanesi",
"Özel İskenderun Gelişim Hastanesi",
"Özel Kent Acıbadem Hastanesi",
"Özel Körfez Hastanesi",
"Özel Liv Hastanesi",
"Özel Medifema Hastanesi",
"Özel Medinova Hastanesi",
"Özel Sekiz Eylül Hastanesi",
"Özel Su Hastanesi",
"Özel Şifa Hastanesi",
"Özel Ümit Hastanesi",
"Özel Yaşam Hastanesi",
"Özel Yenişehir Hastanesi",
"Pamukkale Üniversitesi",
"Pendik Bölge Hastanesi",
"Reyap Çorlu Hastanesi",
"Sakarya Eğitim ve Araştırma Hastanesi",
"Samsun Atasam Hastanesi",
"Samsun Eğitim ve Araştırma Hastanesi",
"Sancaktepe Şehit Prof. Dr. İlhan Varank Eğitim ve Araştırma Hastanesi",
"Sani Konukoğlu Hastanesi",
"Selçuk Üniversitesi Tıp Fakültesi",
"Sinop Atatürk Devlet Hastanesi",
"Sivas Numune Hastanesi",
"Siverek Devlet Hastanesi",
"Siyami Ersek GKDC Eğitim ve Araştırma Hastanesi",
"Sultangazi Haseki Eğitim ve Araştırma Hastanesi",
"Sütçü İmam Üniversitesi",
"Şanlıurfa Eğitim Araştırma ve Uygulama Hastanesi",
"Şanlıurfa Eğitim ve Araştırma Hastanesi",
"Şifa Üniversitesi",
"Şişli Hamidiye Etfal Eğitim ve Araştırma Hastanesi",
"Tedris Cerrahiyye Klinika",
"Tekden Hastanesi",
"Tekirdağ Devlet Hastanesi",
"Tepecik Eğitim ve Araştırma Hastanesi",
"Tınaztepe Galen Hastanesi",
"Tınaztepe Üniversite Hastanesi",
"TOBB ETU Hastanesi",
"Tokat Devlet Hastanesi",
"Trabzon Kanuni Eğitim Ve Araştırma Hastanesi",
"Trakya Üniversitesi",
"Tunceli Devlet Hastanesi",
"Ufuk Üniversitesi",
"Uşak Eğitim Araştırma Hastanesi",
"Uşak Eğt.Arş.Hastanesi",
"Uşak Medical Park Hastanesi",
"Uşak Üniversite Hastanesi",
"Ümraniye Devlet Hastanesi",
"Ümraniye Eğitim ve Araştırma Hastanesi",
"Van Bölge Hastanesi",
"Van Bölge Hastanesi 2",
"VM Medical Park Kocaeli Hastanesi",
"VM Medical Park Mersin Hastanesi",
"Yalova Atakent Hastanesi",
"Yalova Devlet Hastanesi (Kamu Has.Bir.)",
"Yeditepe Üniversitesi Hastanesi",
"Yeni Yüzyıl Üniversitesi Özel Gaziosmanpaşa Hastanesi",
"Yücelen Hastanesi",
"Zilan Hastanesi"
];

export const isValidHospital = (value: string) => {
  return HOSPITALS.some(
    (name) => name.toLowerCase() === value.trim().toLowerCase()
  );
};
