// Yetkili hastane listesi (oto-tamamlama ve doğrulama için)
export const HOSPITALS: string[] = [
  "100. Yıl Hastanesi",
  "100. Yıl Üniversitesi",
  "Abant İzzet Baysal Üniversitesi",
  "Acıbadem Adana Hastanesi",
  "Acıbadem Bakırköy Hastanesi",
  "Acıbadem Bursa Hastanesi",
  "Acıbadem Eskişehir Hastanesi",
  "Acıbadem Kadıköy Hastanesi",
  "Acıbadem Kocaeli Hastanesi",
  "Acıbadem Maslak Hastanesi",
  "Adana Ortadoğu Hastanesi",
  "Adana Seyhan Uygulama ve Araştırma Hastanesi",
  "Adnan Menderes Üniversitesi",
  "Ahi Evren GKDC Eğitim ve Araştırma Hastanesi",
  "Aile Hastanesi Bahçelievler",
  "Akay Hastanesi",
  "Akdeniz Üniversitesi",
  "Aksaray Devlet Hastanesi",
  "Amerikan Hastanesi",
  "Anadolu Sağlık Merkezi",
  "Ankara Atatürk Eğitim ve Araştırma Hastanesi",
  "Ankara Hastanesi",
  "Ankara Numune Eğitim ve Araştırma Hastanesi",
  "Ankara Üniversitesi Cebeci Kalp Merkezi",
  "Ankara Yüksek İhtisas Hastanesi",
  "Atatürk Üniversitesi",
  "Avicenna Esenler Hastanesi",
  "Aydın Devlet Hastanesi",
  "Bağcılar Eğitim ve Araştırma Hastanesi",
  "Bahar Hastanesi",
  "Baki Uzun Hastanesi",
  "Bakırköy Sadi Konuk Eğitim ve Araştırma Hastanesi",
  "Balıkesir Devlet Hastanesi",
  "Balıkesir Sevgi Hastanesi",
  "Başkent Üniversitesi Adana Yüreğir",
  "Başkent Üniversitesi Ankara",
  "Başkent Üniversitesi İstanbul",
  "Başkent Üniversitesi Konya",
  "Bayındır Hastanesi Ankara",
  "Bayındır İçerenköy Hastanesi",
  "Behçet Uz Eğitim ve Araştırma Çocuk Hastanesi",
  "Bezm-i Alem Üniversitesi",
  "Bilgi Hastanesi",
  "Buca Seyfi Demirsoy Devlet Hastanesi",
  "Bursa Anadolu Hastanesi",
  "Bursa Devlet Hastanesi",
  "Bursa Yüksek İhtisas Hastanesi",
  "Çağ Hastanesi",
  "Çakmak Erdem Hastanesi",
  "Çamlıca Erdem Hastanesi",
  "Çankaya Hastanesi",
  "Çekirge Kalp ve Aritmi Hastanesi",
  "Celal Bayar Üniversitesi Hastanesi",
  "Central Hastanesi",
  "Çorlu Şifa Hastanesi",
  "Çukurova Üniversitesi",
  "Cumhuriyet Üniversitesi",
  "Damla Hastanesi",
  "Defne Hastanesi",
  "Denizli Devlet Hastanesi",
  "Dicle Üniversitesi",
  "Dışkapı Yıldırım Beyazıt Eğitim ve Araştırma Hastanesi",
  "Diyarbakır Eğitim ve Araştırma Hastanesi",
  "Doğan Hastanesi",
  "Doğuş Hastanesi",
  "Dokuz Eylül Üniversitesi",
  "Dr.Ersin Arslan Devlet Hastanesi",
  "Dumlupınar Üniversitesi Evliya Çelebi Eğitim ve Araştırma Hastanesi",
  "Düzce Üniversitesi",
  "Ege Üniversitesi",
  "Elazığ Eğitim ve Araştırma Hastanesi",
  "Emsey Hospital",
  "Erciyes Üniversitesi",
  "Ersin Arslan Devlet Hastanesi",
  "Erzincan Üniversitesi Mengücek Gazi Eğt. Araşt. Hast.",
  "Etimed Hastanesi",
  "Etlik İhtisas Hastanesi",
  "Fethiye Lokman Hekim Hastanesi",
  "Fırat Üniversitesi",
  "Florence Nightingale Kadıköy Hastanesi",
  "Florence Nightingale Şişli Hastanesi",
  "Gazi Hastanesi",
  "Gazi Üniversitesi",
  "Gaziantep Üniversitesi",
  "Gaziosmanpaşa Üniversitesi",
  "Giresun Özel Ada Hastanesi",
  "Gülhane Askeri Tıp Akademisi",
  "Gülhane Askeri Tıp Akademisi Haydarpaşa Eğitim Hastanesi",
  "Güven Hastanesi",
  "Hacettepe Üniversitesi",
  "Harran Üniversitesi",
  "Haseki Eğitim ve Araştırma 29 Mayıs Hastanesi",
  "Hisar Intercontinental Hospital",
  "İnönü Üniversitesi",
  "International Hospital",
  "İskenderun Gelişim Hastanesi",
  "İstanbul Üniversitesi Çapa Hastanesi",
  "İstanbul Üniversitesi Cerrahpaşa Hastanesi",
  "İstanbul Üniversitesi Haseki Hastanesi",
  "İzmir Atatürk Eğitim ve Araştırma Hastanesi",
  "İzmir Üniversitesi Medicalpark Hastanesi",
  "Kadıköy Alman Hastanesi",
  "Kahramanmaraş Devlet Hastanesi",
  "Karadeniz Teknik Üniversitesi Farabi Hastanesi",
  "Karaelmas Üniversitesi",
  "Kartal Koşuyolu Eğitim ve Araştırma Hastanesi",
  "Kavaklıdere Umut Hastanesi",
  "Kent Hastanesi",
  "Kırıkkale Üniversitesi",
  "Kocaeli Üniversitesi",
  "Kocatepe Üniversitesi",
  "Kolan Beylikdüzü Hastanesi",
  "Konak Hastanesi",
  "Körfez Hastanesi",
  "Koru Hastanesi",
  "Kudret International",
  "Kuşadası Universal Hospital",
  "Kütahya Eğitim ve Araştırma Hastanesi",
  "Lokman Hekim Hastanesi",
  "Malatya Gözde Hastanesi",
  "Maltepe Üniversitesi",
  "Marmara Üniversitesi",
  "Medical Park Antalya Hastanesi",
  "Medical Park Bahçelievler Hastanesi",
  "Medical Park Bursa Hastanesi",
  "Medical Park Elazığ Hastanesi",
  "Medical Park Fatih Hastanesi",
  "Medical Park Gaziantep Hastanesi",
  "Medical Park Gebze Hastanesi",
  "Medical Park Göztepe Hastanesi",
  "Medical Park Ordu Hastanesi",
  "Medical Park Samsun Hastanesi",
  "Medical Park Tarsus Hastanesi",
  "Medical Park Tokat Hastanesi",
  "Medicana Bahçelievler Hastanesi",
  "Medicana Çamlıca Hastanesi",
  "Medicana International Ankara Hastanesi",
  "Medicana International İstanbul Hastanesi",
  "Medicana International Konya Hastanesi",
  "Medicana International Samsun Hastanesi",
  "Medicana International Sivas Hastanesi",
  "Medicine Hastanesi",
  "Medipol Üniversitesi Hastanesi",
  "Medistate Hastanesi",
  "Medline Hastanesi Adana",
  "Medline Hastanesi Antalya",
  "Medline Hastanesi Aydın",
  "Medline Hastanesi Eskişehir",
  "Medline Hastanesi Konya",
  "Mehmet Akif Ersoy Eğitim ve Araştırma Hastanesi",
  "Memorial Ataşehir Hastanesi",
  "Memorial Hastanesi",
  "Memorial Şişli Hastanesi",
  "Meram Tıp Fakültesi Hastanesi",
  "Mersin Devlet Hastanesi",
  "Mersin Ortadoğu Hastanesi",
  "Mersin Üniversitesi",
  "Muğla Üniversite Hastanesi",
  "Muğla Yücelen Hastanesi",
  "Muş Devlet Hastanesi",
  "Mustafa Kemal Üniversitesi",
  "Namık Kemal Üniversitesi",
  "Numune Hastanesi Sivas",
  "Ondokuz Mayıs Üniversitesi",
  "Onsekiz Mart Üniversitesi",
  "Ordu Üniversitesi",
  "OSM Ortadoğu Hastanesi",
  "Osmangazi Üniversitesi",
  "Özel Ada Hastanesi",
  "Özel Adana Hastanesi",
  "Özel Akut Hastanesi",
  "Özel Atakalp Hastanesi",
  "Özel Ege Sağlık Hastanesi",
  "Özel Ege Tıp Hizmetleri",
  "Özel Grand Medical",
  "Özel Hizmet Hastanesi",
  "Özel IMC Hastanesi",
  "Özel İskenderun Gelişim Hastanesi",
  "Özel Körfez Hastanesi",
  "Özel Liv Hastanesi",
  "Özel Sekiz Eylül Hastanesi",
  "Özel Şifa Hastanesi",
  "Özel Su Hastanesi",
  "Özel Ümit Hastanesi",
  "Pamukkale Üniversitesi",
  "Pendik Bölge Hastanesi",
  "Reyap Çorlu Hastanesi",
  "Samsun Eğitim ve Araştırma Hastanesi",
  "Sani Konukoğlu Hastanesi",
  "Şanlıurfa Eğitim ve Araştırma Hastanesi",
  "Selçuk Üniversitesi Tıp Fakültesi",
  "Şifa Üniversitesi",
  "Siyami Ersek GKDC Eğitim ve Araştırma Hastanesi",
  "Sütçü İmam Üniversitesi",
  "Tekden Hastanesi",
  "Tekirdağ Devlet Hastanesi",
  "Tepecik Eğitim ve Araştırma Hastanesi",
  "TOBB ETU Hastanesi",
  "Trakya Üniversitesi",
  "Turgut Özal Üniversitesi Araştırma ve Uygulama Hastanesi",
  "Ufuk Üniversitesi",
  "Van Bölge Hastanesi",
  "Yeditepe Üniversitesi Hastanesi",
  "Yücelen Hastanesi",
  "Samsun Atasam Hastanesi",
  "Natomed Hastanesi",
  "Medicalpark Silivri Hastanesi",
  "Acıbadem Atakent Hastanesi",
  "Avcılar Hospital",
  "Avrasya Hospital",
  "VM Medical Park Kocaeli Hastanesi",
  "Özel Egepol",
  "Afyon Park Hastanesi",
  "Herbi Hospital",
  "Eskişehir Anadolu Hastanesi",
  "Giresun Üniversitesi Eğitim ve Araştırma Hastanesi",
  "Kolan International Hospital",
  "Kolan Bayrampaşa Hastanesi",
  "Koç Üniversitesi Tıp Fakültesi Hastanesi",
  "Adana Özel Sağlık Hastanesi",
  "Uşak Medical Park Hastanesi",
  "Gəncə Beynəlxalq Hospitalı",
  "Azərbaycan Tibb Universiteti Cərahiyyə Xəstəxanası",
  "Medystyle Hospital",
  "Malatya Gözde Akademi Hastanesi",
  "Medikar Hastanesi",
  "Van Bölge Hastanesi 2",
  "Medeniyet Üniversitesi Göztepe Eğitim Ve Araştırma Hastanesi",
  "İstinye Üniversitesi Liv Hospital Hastanesi Bahçeşehir",
  "Sinop Atatürk Devlet Hastanesi",
  "Özel Yaşam Hastanesi",
  "Avrupa Şafak Hastanesi",
  "Ümraniye Eğitim ve Araştırma Hastanesi",
  "Kilis Devlet Hastanesi",
  "Acıbadem Altunizade Hastanesi",
  "İ.A.Ü. VM Medical Park Florya Hastanesi",
  "Çiğli Bölge Hastanesi",
  "Okmeydanı Eğitim Hastanesi",
  "Güney Adana Hastanesi",
  "Kıbrıs Dr Burhan Nalbantoğlu Devlet Hastanesi",
  "Yeni Yüzyıl Üniversitesi Özel Gaziosmanpaşa Hastanesi",
  "Özel Adatıp Hastanesi",
  "Biruni Üniversite Hastanesi",
  "Memorial Bahçelievler Hastanesi",
  "29 Mayıs Devlet Hastanesi",
  "Özel Medinova Hastanesi",
  "VM Medical Park Mersin Hastanesi",
  "İstinye Üniversitesi Liv Hospital Hastanesi GOP",
  "Mehmet Akif İnan Eğt.Arş.Hastanesi"
];

export const isValidHospital = (value: string) => {
  return HOSPITALS.some(
    (name) => name.toLowerCase() === value.trim().toLowerCase()
  );
};
